### PR TITLE
Return GATT_SUCCESS when Descriptor is read

### PR DESCRIPTION
**Pull request by carlospuk**
Existing code was returning GATT_FAILURE for all code paths in onDescriptorReadRequest - if the config descriptor matches and is valid, GATT_SUCCESS should be returned along with the correct value for ENABLE/DISABLE notification

### CODE REVIEW

**Comment by hammmmy** [comment]
Got the same issue when i tested it https://github.com/androidthings/sample-bluetooth-le-gattserver/pull/3

**Comment by devunwired** [comment]
Thanks for catching this!

**Comment by hammmmy** [comment]
#3 fixed the same issue.. anyways thanks for fixing this finally

**Comment by devunwired** [comment]
@hammmmy Yes, but #3 also included several other changes unrelated to the issue described. In the future, I would recommend splitting unrelated changes into separate PRs.

**Pull request merged**
